version: '3'

services:
  collectd:
    image: derpw/fritzcollectd:latest
    container_name: fritzcollectd

    environment:
      - FRITZ_IP=192.168.178.1
      - FRITZ_USER=<user>
      - FRITZ_PASSWORD=<passwd>
      - EP_HOST=0.0.0.0 # address
      - EP_PORT=25826   # port where you configured [collectd] influxdb

    ports:
      - "25826:25826"
